name: ponyc update breakage test

on:
  repository_dispatch:
    types: [shared-docker-linux-builders-updated]

jobs:
  test-libressl-3_4_1-vs-ponyc-latest:
    name: LibreSSL 3.4.1 with ponyc main
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-libressl-3.4.1:latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test config=debug ssl=0.9.0
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip@35d7ad8e98444f894dcfe1d4e17332581d28ebeb
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  test-openssl-1_1_1l-vs-ponyc-latest:
    name: OpenSSL 1.1.1l with ponyc main
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_1.1.1l:latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test config=debug ssl=1.1.x
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip@35d7ad8e98444f894dcfe1d4e17332581d28ebeb
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
